# Generated by Django 3.2.2 on 2021-07-21 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now=True)),
                ('ordered', models.BooleanField(default=False)),
                ('checkout_address', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, null=True)),
                ('amount', models.FloatField()),
                ('productinfo', models.CharField(max_length=100, null=True)),
                ('hash', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Order.orders')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
